name: autoboost

channels:
  - conda-forge
  - bioconda

dependencies:
  - python>=3.9
  - pip
  - xgboost
  - scikit-learn
  - seaborn
  - lightgbm
  - tqdm

  # testing
  - pytest
  - pytest-flake8
  - pytest-cov
  - pydocstyle

pip:
  - pytest-pydocstyle
  - flake8-html
  - genbadge